### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by aclavin-eab** [Annikizzle/TriviaGame#1]
Excellent Read me! Love the theme for the game, learned a good bit too! HTML looks great, except all of the values for your attributes should be with double quotes, not single or none at all. HTML is extremely fault tolerant so it works, but it is best practice / semantically illegal not to  to use double quotes around everything in html (and single around most in javascript is a standard practice as well).

Your CSS has pretty inconsistent spacing, try to make sure that you fix that to a consistent 2 or 4 spaces per indentation across the file.

Javascript is straightforward and easy to follow. Some peculiarities to your indentation in the object in the beginning (usually you don't close an object and open a new one on the same line, but that will come with practice) also either use var once and commas for different variable statements or put each var on a new line at line 44. Most importantly though is declare all your vars at the top of the scope they are in, this is just best practice for ease of reading. Your indentation looks big, like 8 spaces, but maybe it's just my eyes, either way, it's consistent so kudos! Keep it up!

**Comment by Annikizzle** [comment]
I find that first paragraph terribly confusing--you say to use double quotes, but then not to use double quotes? Please clarify!

Also, I understand and appreciate your comments about the spacing, but I thought we would be graded on the functionality of the game. A lot of your spacing comments sound opinion-based, so while I appreciate that feedback, I don't believe that should be the basis for my grade.
